# Generated by Django 3.0.3 on 2020-09-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('headerimg', models.TextField()),
                ('socketid', models.TextField()),
                ('isonline', models.TextField()),
            ],
            options={
                'db_table': 'wxchart_user',
            },
        ),
    ]
